// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	changeBinding: (id: string, binding: string) => typedError<BindingResponse, string>(__TAURI_INVOKE("change_binding", { id, binding })),
	resetBinding: (id: string) => typedError<BindingResponse, string>(__TAURI_INVOKE("reset_binding", { id })),
	changePttSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_ptt_setting", { enabled })),
	changeAudioFeedbackSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_audio_feedback_setting", { enabled })),
	changeAudioFeedbackVolumeSetting: (volume: number | null) => typedError<null, string>(__TAURI_INVOKE("change_audio_feedback_volume_setting", { volume })),
	changeSoundThemeSetting: (theme: string) => typedError<null, string>(__TAURI_INVOKE("change_sound_theme_setting", { theme })),
	changeThemeSetting: (theme: string) => typedError<null, string>(__TAURI_INVOKE("change_theme_setting", { theme })),
	changeStartHiddenSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_start_hidden_setting", { enabled })),
	changeAutostartSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_autostart_setting", { enabled })),
	changeTranslateToEnglishSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_translate_to_english_setting", { enabled })),
	changeSelectedLanguageSetting: (language: string) => typedError<null, string>(__TAURI_INVOKE("change_selected_language_setting", { language })),
	changeOverlayPositionSetting: (position: string) => typedError<null, string>(__TAURI_INVOKE("change_overlay_position_setting", { position })),
	changeOverlayStyleSetting: (style: string) => typedError<null, string>(__TAURI_INVOKE("change_overlay_style_setting", { style })),
	changeDebugModeSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_debug_mode_setting", { enabled })),
	changeWordCorrectionThresholdSetting: (threshold: number | null) => typedError<null, string>(__TAURI_INVOKE("change_word_correction_threshold_setting", { threshold })),
	changeExtraRecordingBufferSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_extra_recording_buffer_setting", { ms })),
	changePasteDelayMsSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_paste_delay_ms_setting", { ms })),
	changePasteDelayAfterMsSetting: (ms: number) => typedError<null, string>(__TAURI_INVOKE("change_paste_delay_after_ms_setting", { ms })),
	changePasteMethodSetting: (method: string) => typedError<null, string>(__TAURI_INVOKE("change_paste_method_setting", { method })),
	getAvailableTypingTools: () => __TAURI_INVOKE<string[]>("get_available_typing_tools"),
	changeTypingToolSetting: (tool: string) => typedError<null, string>(__TAURI_INVOKE("change_typing_tool_setting", { tool })),
	changeExternalScriptPathSetting: (path: string | null) => typedError<null, string>(__TAURI_INVOKE("change_external_script_path_setting", { path })),
	changeClipboardHandlingSetting: (handling: string) => typedError<null, string>(__TAURI_INVOKE("change_clipboard_handling_setting", { handling })),
	changeAutoSubmitSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_auto_submit_setting", { enabled })),
	changeAutoSubmitKeySetting: (key: string) => typedError<null, string>(__TAURI_INVOKE("change_auto_submit_key_setting", { key })),
	changePostProcessEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_post_process_enabled_setting", { enabled })),
	changeExperimentalEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_experimental_enabled_setting", { enabled })),
	changePostProcessBaseUrlSetting: (providerId: string, baseUrl: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl })),
	changePostProcessApiKeySetting: (providerId: string, apiKey: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey })),
	changePostProcessModelSetting: (providerId: string, model: string) => typedError<null, string>(__TAURI_INVOKE("change_post_process_model_setting", { providerId, model })),
	setPostProcessProvider: (providerId: string) => typedError<null, string>(__TAURI_INVOKE("set_post_process_provider", { providerId })),
	fetchPostProcessModels: (providerId: string) => typedError<string[], string>(__TAURI_INVOKE("fetch_post_process_models", { providerId })),
	addPostProcessPrompt: (name: string, prompt: string) => typedError<LLMPrompt, string>(__TAURI_INVOKE("add_post_process_prompt", { name, prompt })),
	updatePostProcessPrompt: (id: string, name: string, prompt: string) => typedError<null, string>(__TAURI_INVOKE("update_post_process_prompt", { id, name, prompt })),
	deletePostProcessPrompt: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_post_process_prompt", { id })),
	setPostProcessSelectedPrompt: (id: string) => typedError<null, string>(__TAURI_INVOKE("set_post_process_selected_prompt", { id })),
	updateCustomWords: (words: string[]) => typedError<null, string>(__TAURI_INVOKE("update_custom_words", { words })),
	/**
	 *  Temporarily unregister a binding while the user is editing it in the UI.
	 *  This avoids firing the action while keys are being recorded.
	 */
	suspendBinding: (id: string) => typedError<null, string>(__TAURI_INVOKE("suspend_binding", { id })),
	/**  Re-register the binding after the user has finished editing. */
	resumeBinding: (id: string) => typedError<null, string>(__TAURI_INVOKE("resume_binding", { id })),
	changeMuteWhileRecordingSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_mute_while_recording_setting", { enabled })),
	changeAppendTrailingSpaceSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_append_trailing_space_setting", { enabled })),
	changeLazyStreamCloseSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_lazy_stream_close_setting", { enabled })),
	changeVadEnabledSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_vad_enabled_setting", { enabled })),
	changeAppLanguageSetting: (language: string) => typedError<null, string>(__TAURI_INVOKE("change_app_language_setting", { language })),
	changeUpdateChecksSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_update_checks_setting", { enabled })),
	changeShowWhatsNewOnUpdateSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_show_whats_new_on_update_setting", { enabled })),
	changeWhatsNewLastSeenVersionSetting: (version: string) => typedError<null, string>(__TAURI_INVOKE("change_whats_new_last_seen_version_setting", { version })),
	/**
	 *  Change the keyboard implementation with runtime switching.
	 *  This will unregister all shortcuts from the old implementation,
	 *  validate shortcuts for the new implementation (resetting invalid ones to defaults),
	 *  and register them with the new implementation.
	 */
	changeKeyboardImplementationSetting: (implementation: string) => typedError<ImplementationChangeResult, string>(__TAURI_INVOKE("change_keyboard_implementation_setting", { implementation })),
	/**  Get the current keyboard implementation */
	getKeyboardImplementation: () => __TAURI_INVOKE<string>("get_keyboard_implementation"),
	changeShowTrayIconSetting: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("change_show_tray_icon_setting", { enabled })),
	changeTranscribeAcceleratorSetting: (accelerator: TranscribeAcceleratorSetting) => typedError<null, string>(__TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator })),
	changeOrtAcceleratorSetting: (accelerator: OrtAcceleratorSetting) => typedError<null, string>(__TAURI_INVOKE("change_ort_accelerator_setting", { accelerator })),
	changeTranscribeGpuDevice: (device: number) => typedError<null, string>(__TAURI_INVOKE("change_transcribe_gpu_device", { device })),
	/**
	 *  Return which accelerators and GPU devices are available for this build.
	 * 
	 *  First-call cost is dominated by enumerating GPU devices through the
	 *  transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
	 *  probes hardware. Run it on the blocking pool so the webview thread
	 *  stays responsive — see also the startup pre-warm in `lib.rs`.
	 */
	getAvailableAccelerators: () => __TAURI_INVOKE<AvailableAccelerators>("get_available_accelerators"),
	/**  Start key recording mode */
	startHandyKeysRecording: (bindingId: string) => typedError<null, string>(__TAURI_INVOKE("start_handy_keys_recording", { bindingId })),
	/**  Stop key recording mode */
	stopHandyKeysRecording: () => typedError<null, string>(__TAURI_INVOKE("stop_handy_keys_recording")),
	triggerUpdateCheck: () => typedError<null, string>(__TAURI_INVOKE("trigger_update_check")),
	showMainWindowCommand: () => typedError<null, string>(__TAURI_INVOKE("show_main_window_command")),
	cancelOperation: () => __TAURI_INVOKE<void>("cancel_operation"),
	isPortable: () => __TAURI_INVOKE<boolean>("is_portable"),
	getAppDirPath: () => typedError<string, string>(__TAURI_INVOKE("get_app_dir_path")),
	getAppSettings: () => typedError<AppSettings_Serialize, string>(__TAURI_INVOKE("get_app_settings")),
	getDefaultSettings: () => typedError<AppSettings_Serialize, string>(__TAURI_INVOKE("get_default_settings")),
	getLogDirPath: () => typedError<string, string>(__TAURI_INVOKE("get_log_dir_path")),
	setLogLevel: (level: LogLevel) => typedError<null, string>(__TAURI_INVOKE("set_log_level", { level })),
	openRecordingsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_recordings_folder")),
	openLogDir: () => typedError<null, string>(__TAURI_INVOKE("open_log_dir")),
	openAppDataDir: () => typedError<null, string>(__TAURI_INVOKE("open_app_data_dir")),
	/**
	 *  Check if Apple Intelligence is available on this device.
	 *  Called by the frontend when the user selects Apple Intelligence provider.
	 */
	checkAppleIntelligenceAvailable: () => __TAURI_INVOKE<boolean>("check_apple_intelligence_available"),
	/**
	 *  Try to initialize Enigo (keyboard/mouse simulation).
	 *  On macOS, this will return an error if accessibility permissions are not granted.
	 */
	initializeEnigo: () => typedError<null, string>(__TAURI_INVOKE("initialize_enigo")),
	/**
	 *  Initialize keyboard shortcuts.
	 *  On macOS, this should be called after accessibility permissions are granted.
	 *  This is idempotent - calling it multiple times is safe.
	 */
	initializeShortcuts: () => typedError<null, string>(__TAURI_INVOKE("initialize_shortcuts")),
	getAvailableModels: () => typedError<ModelInfo[], string>(__TAURI_INVOKE("get_available_models")),
	getModelInfo: (modelId: string) => typedError<{
	id: string,
	name: string,
	description: string,
	filename: string,
	source: ModelSource,
	size_mb: number,
	is_downloaded: boolean,
	is_downloading: boolean,
	partial_size: number,
	is_directory: boolean,
	engine_type: EngineType,
	accuracy_score: number | null,
	speed_score: number | null,
	supports_translation: boolean,
	is_recommended: boolean,
	supported_languages: string[],
	supports_language_selection: boolean,
	is_custom: boolean,
	supports_streaming: boolean,
	supports_language_detection: boolean,
} | null, string>(__TAURI_INVOKE("get_model_info", { modelId })),
	downloadModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("download_model", { modelId })),
	deleteModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("delete_model", { modelId })),
	cancelDownload: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_download", { modelId })),
	setActiveModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("set_active_model", { modelId })),
	getCurrentModel: () => typedError<string, string>(__TAURI_INVOKE("get_current_model")),
	getTranscriptionModelStatus: () => typedError<string | null, string>(__TAURI_INVOKE("get_transcription_model_status")),
	isModelLoading: () => typedError<boolean, string>(__TAURI_INVOKE("is_model_loading")),
	/**
	 *  Re-scan local sources (custom models dir + shared HF cache) for models added
	 *  since launch
	 */
	rescanLocalModels: () => typedError<null, string>(__TAURI_INVOKE("rescan_local_models")),
	updateMicrophoneMode: (alwaysOn: boolean) => typedError<null, string>(__TAURI_INVOKE("update_microphone_mode", { alwaysOn })),
	getMicrophoneMode: () => typedError<boolean, string>(__TAURI_INVOKE("get_microphone_mode")),
	getWindowsMicrophonePermissionStatus: () => __TAURI_INVOKE<WindowsMicrophonePermissionStatus>("get_windows_microphone_permission_status"),
	openMicrophonePrivacySettings: () => typedError<null, string>(__TAURI_INVOKE("open_microphone_privacy_settings")),
	getAvailableMicrophones: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_available_microphones")),
	setSelectedMicrophone: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_selected_microphone", { deviceName })),
	getSelectedMicrophone: () => typedError<string, string>(__TAURI_INVOKE("get_selected_microphone")),
	getAvailableOutputDevices: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_available_output_devices")),
	setSelectedOutputDevice: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_selected_output_device", { deviceName })),
	getSelectedOutputDevice: () => typedError<string, string>(__TAURI_INVOKE("get_selected_output_device")),
	playTestSound: (soundType: string) => __TAURI_INVOKE<void>("play_test_sound", { soundType }),
	checkCustomSounds: () => __TAURI_INVOKE<CustomSounds>("check_custom_sounds"),
	setClamshellMicrophone: (deviceName: string) => typedError<null, string>(__TAURI_INVOKE("set_clamshell_microphone", { deviceName })),
	getClamshellMicrophone: () => typedError<string, string>(__TAURI_INVOKE("get_clamshell_microphone")),
	isRecording: () => __TAURI_INVOKE<boolean>("is_recording"),
	setModelUnloadTimeout: (timeout: ModelUnloadTimeout) => __TAURI_INVOKE<void>("set_model_unload_timeout", { timeout }),
	getModelLoadStatus: () => typedError<ModelLoadStatus, string>(__TAURI_INVOKE("get_model_load_status")),
	unloadModelManually: () => typedError<null, string>(__TAURI_INVOKE("unload_model_manually")),
	getHistoryEntries: (cursor: number | null, limit: number | null) => typedError<PaginatedHistory, string>(__TAURI_INVOKE("get_history_entries", { cursor, limit })),
	toggleHistoryEntrySaved: (id: number) => typedError<null, string>(__TAURI_INVOKE("toggle_history_entry_saved", { id })),
	getAudioFilePath: (fileName: string) => typedError<string, string>(__TAURI_INVOKE("get_audio_file_path", { fileName })),
	deleteHistoryEntry: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_history_entry", { id })),
	retryHistoryEntryTranscription: (id: number) => typedError<null, string>(__TAURI_INVOKE("retry_history_entry_transcription", { id })),
	updateHistoryLimit: (limit: number) => typedError<null, string>(__TAURI_INVOKE("update_history_limit", { limit })),
	updateRecordingRetentionPeriod: (period: string) => typedError<null, string>(__TAURI_INVOKE("update_recording_retention_period", { period })),
	/**
	 *  Stub implementation for non-macOS platforms
	 *  Always returns false since laptop detection is macOS-specific
	 */
	isLaptop: () => typedError<boolean, string>(__TAURI_INVOKE("is_laptop")),
};

/** Events */
export const events = {
	historyUpdatePayload: makeEvent<HistoryUpdatePayload>("history-update-payload"),
	streamPhaseEvent: makeEvent<StreamPhaseEvent_Deserialize>("stream-phase-event"),
	streamTextEvent: makeEvent<StreamTextEvent>("stream-text-event"),
};

/* Types */
/**
 *  The container-level `serde(default)` (backed by the `Default` impl below)
 *  guarantees every field — including ones added in the future — falls back to
 *  its `get_default_settings()` value when missing from a stored settings
 *  object, so a partial store can never fail the whole load (#1619).
 *  Field-level defaults below take precedence where present.
 */
export type AppSettings = AppSettings_Serialize | AppSettings_Deserialize;

/**
 *  The container-level `serde(default)` (backed by the `Default` impl below)
 *  guarantees every field — including ones added in the future — falls back to
 *  its `get_default_settings()` value when missing from a stored settings
 *  object, so a partial store can never fail the whole load (#1619).
 *  Field-level defaults below take precedence where present.
 */
export type AppSettings_Deserialize = {
	/**
	 *  Internal settings schema marker for one-time migrations. Fresh installs
	 *  start at the current version; existing stores missing this key are
	 *  treated as version 0 and migrated forward.
	 */
	settings_schema_version?: number,
	/**
	 *  Defaults to empty on partial stores; the load path merges in the
	 *  default bindings for any missing keys before the settings are used.
	 */
	bindings?: { [key in string]: ShortcutBinding },
	push_to_talk?: boolean,
	audio_feedback?: boolean,
	audio_feedback_volume?: number | null,
	sound_theme?: SoundTheme,
	start_hidden?: boolean,
	autostart_enabled?: boolean,
	update_checks_enabled?: boolean,
	show_whats_new_on_update?: boolean,
	/**
	 *  The app version whose What's New the user has already seen. Fresh installs
	 *  default to the current version (nothing is "new" to them). Existing users
	 *  upgrading from before this key existed are blanked by the migration so they
	 *  see the current release's notes — see `apply_settings_migrations`.
	 */
	whats_new_last_seen_version?: string,
	selected_model?: string,
	onboarding_completed?: boolean,
	always_on_microphone?: boolean,
	selected_microphone?: string | null,
	clamshell_microphone?: string | null,
	selected_output_device?: string | null,
	translate_to_english?: boolean,
	selected_language?: string,
	overlay_position?: OverlayPosition_Deserialize,
	debug_mode?: boolean,
	log_level?: LogLevel,
	custom_words?: string[],
	model_unload_timeout?: ModelUnloadTimeout,
	word_correction_threshold?: number | null,
	history_limit?: number,
	recording_retention_period?: RecordingRetentionPeriod,
	paste_method?: PasteMethod,
	clipboard_handling?: ClipboardHandling,
	auto_submit?: boolean,
	auto_submit_key?: AutoSubmitKey,
	post_process_enabled?: boolean,
	post_process_provider_id?: string,
	post_process_providers?: PostProcessProvider[],
	post_process_api_keys?: SecretMap,
	post_process_models?: { [key in string]: string },
	post_process_prompts?: LLMPrompt[],
	post_process_selected_prompt_id?: string | null,
	mute_while_recording?: boolean,
	append_trailing_space?: boolean,
	app_language?: string,
	theme?: Theme,
	experimental_enabled?: boolean,
	lazy_stream_close?: boolean,
	keyboard_implementation?: KeyboardImplementation,
	show_tray_icon?: boolean,
	paste_delay_ms?: number,
	paste_delay_after_ms?: number,
	typing_tool?: TypingTool,
	external_script_path?: string | null,
	custom_filler_words?: string[] | null,
	transcribe_accelerator?: TranscribeAcceleratorSetting,
	ort_accelerator?: OrtAcceleratorSetting,
	transcribe_gpu_device?: number,
	extra_recording_buffer_ms?: number,
	vad_enabled?: boolean,
	/**
	 *  Which recording overlay to show: None / Minimal / Live. Streaming mode is
	 *  not gated on this — that follows model capability. Migrated from the old
	 *  `overlay_position` (position `none` → style `None`).
	 */
	overlay_style?: OverlayStyle,
};

/**
 *  The container-level `serde(default)` (backed by the `Default` impl below)
 *  guarantees every field — including ones added in the future — falls back to
 *  its `get_default_settings()` value when missing from a stored settings
 *  object, so a partial store can never fail the whole load (#1619).
 *  Field-level defaults below take precedence where present.
 */
export type AppSettings_Serialize = {
	/**
	 *  Internal settings schema marker for one-time migrations. Fresh installs
	 *  start at the current version; existing stores missing this key are
	 *  treated as version 0 and migrated forward.
	 */
	settings_schema_version: number,
	/**
	 *  Defaults to empty on partial stores; the load path merges in the
	 *  default bindings for any missing keys before the settings are used.
	 */
	bindings: { [key in string]: ShortcutBinding },
	push_to_talk: boolean,
	audio_feedback: boolean,
	audio_feedback_volume: number | null,
	sound_theme: SoundTheme,
	start_hidden: boolean,
	autostart_enabled: boolean,
	update_checks_enabled: boolean,
	show_whats_new_on_update: boolean,
	/**
	 *  The app version whose What's New the user has already seen. Fresh installs
	 *  default to the current version (nothing is "new" to them). Existing users
	 *  upgrading from before this key existed are blanked by the migration so they
	 *  see the current release's notes — see `apply_settings_migrations`.
	 */
	whats_new_last_seen_version: string,
	selected_model: string,
	onboarding_completed: boolean,
	always_on_microphone: boolean,
	selected_microphone: string | null,
	clamshell_microphone: string | null,
	selected_output_device: string | null,
	translate_to_english: boolean,
	selected_language: string,
	overlay_position: OverlayPosition_Serialize,
	debug_mode: boolean,
	log_level: LogLevel,
	custom_words: string[],
	model_unload_timeout: ModelUnloadTimeout,
	word_correction_threshold: number | null,
	history_limit: number,
	recording_retention_period: RecordingRetentionPeriod,
	paste_method: PasteMethod,
	clipboard_handling: ClipboardHandling,
	auto_submit: boolean,
	auto_submit_key: AutoSubmitKey,
	post_process_enabled: boolean,
	post_process_provider_id: string,
	post_process_providers: PostProcessProvider[],
	post_process_api_keys: SecretMap,
	post_process_models: { [key in string]: string },
	post_process_prompts: LLMPrompt[],
	post_process_selected_prompt_id: string | null,
	mute_while_recording: boolean,
	append_trailing_space: boolean,
	app_language: string,
	theme: Theme,
	experimental_enabled: boolean,
	lazy_stream_close: boolean,
	keyboard_implementation: KeyboardImplementation,
	show_tray_icon: boolean,
	paste_delay_ms: number,
	paste_delay_after_ms: number,
	typing_tool: TypingTool,
	external_script_path: string | null,
	custom_filler_words: string[] | null,
	transcribe_accelerator: TranscribeAcceleratorSetting,
	ort_accelerator: OrtAcceleratorSetting,
	transcribe_gpu_device: number,
	extra_recording_buffer_ms: number,
	vad_enabled: boolean,
	/**
	 *  Which recording overlay to show: None / Minimal / Live. Streaming mode is
	 *  not gated on this — that follows model capability. Migrated from the old
	 *  `overlay_position` (position `none` → style `None`).
	 */
	overlay_style: OverlayStyle,
};

export type AudioDevice = {
	index: string,
	name: string,
	is_default: boolean,
};

export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter";

export type AvailableAccelerators = {
	transcribe: string[],
	ort: string[],
	gpu_devices: GpuDeviceOption[],
};

export type BindingResponse = {
	success: boolean,
	binding: ShortcutBinding | null,
	error: string | null,
};

export type ClipboardHandling = "dont_modify" | "copy_to_clipboard";

export type CustomSounds = {
	start: boolean,
	stop: boolean,
};

export type EngineType = 
/**
 *  Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 *  Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 *  the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere";

export type GpuDeviceOption = {
	id: number,
	name: string,
	total_vram_mb: number,
};

export type HistoryEntry = {
	id: number,
	file_name: string,
	timestamp: number | null,
	saved: boolean,
	title: string,
	transcription_text: string,
	post_processed_text: string | null,
	post_process_prompt: string | null,
	post_process_requested: boolean,
};

export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number };

/**  Result of changing keyboard implementation */
export type ImplementationChangeResult = {
	success: boolean,
	/**  List of binding IDs that were reset to defaults due to incompatibility */
	reset_bindings: string[],
};

export type KeyboardImplementation = "tauri" | "handy_keys";

export type LLMPrompt = {
	id: string,
	name: string,
	prompt: string,
};

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type ModelInfo = {
	id: string,
	name: string,
	description: string,
	filename: string,
	source: ModelSource,
	size_mb: number,
	is_downloaded: boolean,
	is_downloading: boolean,
	partial_size: number,
	is_directory: boolean,
	engine_type: EngineType,
	accuracy_score: number | null,
	speed_score: number | null,
	supports_translation: boolean,
	is_recommended: boolean,
	supported_languages: string[],
	supports_language_selection: boolean,
	is_custom: boolean,
	supports_streaming: boolean,
	supports_language_detection: boolean,
};

export type ModelLoadStatus = {
	is_loaded: boolean,
	current_model: string | null,
};

/**
 *  Where a model comes from and how Handy obtains it — the routing discriminant
 *  for downloading and on-disk resolution.
 */
export type ModelSource = 
/**  Direct HTTP download from a URL (current blob.handy.computer hosting). */
({ Url: {
	url: string,
	/**  Expected SHA-256 for integrity verification; `None` skips it. */
	sha256: string | null,
} }) & { HuggingFace?: never } | 
/**
 *  A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 *  HF cache (so other tools reuse it). The file within the repo is
 *  [`ModelInfo::filename`].
 */
({ HuggingFace: {
	repo_id: string,
	revision: string,
} }) & { Url?: never } | 
/**
 *  Already present on disk — a user-provided custom model, or one discovered
 *  in a shared cache. Nothing to download.
 */
"Local";

export type ModelUnloadTimeout = "never" | "immediately" | "min2" | "min5" | "min10" | "min15" | "hour1" | "sec15";

export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm";

export type OverlayPosition = OverlayPosition_Serialize | OverlayPosition_Deserialize;

export type OverlayPosition_Deserialize = "top" | "bottom" | "none";

export type OverlayPosition_Serialize = "top" | "bottom";

/**
 *  Which recording overlay to display. `Minimal` and `Live` share one base
 *  (the pill); `Live` grows into the panel that shows live transcription text.
 *  `None` hides the overlay entirely. Decoupled from whether the model runs in
 *  streaming mode (that is driven purely by model capability).
 */
export type OverlayStyle = "none" | "minimal" | "live";

export type PaginatedHistory = {
	entries: HistoryEntry[],
	has_more: boolean,
};

export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script";

export type PermissionAccess = "allowed" | "denied" | "unknown";

export type PostProcessProvider = {
	id: string,
	label: string,
	base_url: string,
	allow_base_url_edit?: boolean,
	models_endpoint?: string | null,
	supports_structured_output?: boolean,
};

export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days3" | "weeks2" | "months3";

export type SecretMap = { [key in string]: string };

export type ShortcutBinding = {
	id: string,
	name: string,
	description: string,
	default_binding: string,
	current_binding: string,
};

export type SoundTheme = "marimba" | "pop" | "custom";

/**  Phase of the streaming overlay card, emitted to drive its UI state. */
export type StreamPhase = 
/**
 *  Receiving audio / live text (or waiting for the stream to begin). Rust
 *  does not emit this today; the frontend starts in this phase and Rust only
 *  emits transitions away from it.
 */
"listening" | 
/**  Finalizing or post-processing — show a spinner. */
"working";

/**  Emitted to switch the streaming overlay to a working spinner. */
export type StreamPhaseEvent = StreamPhaseEvent_Serialize | StreamPhaseEvent_Deserialize;

/**  Emitted to switch the streaming overlay to a working spinner. */
export type StreamPhaseEvent_Deserialize = {
	phase: StreamPhase,
	/**  Present only when `phase` is `Working`. */
	kind: StreamWorkKind | null,
};

/**  Emitted to switch the streaming overlay to a working spinner. */
export type StreamPhaseEvent_Serialize = {
	phase: StreamPhase,
	/**  Present only when `phase` is `Working`. */
	kind?: StreamWorkKind | null,
};

/**
 *  Live transcription snapshot emitted to the overlay during a streaming run.
 *  `committed` is the append-only, flicker-free prefix; `tentative` is the
 *  volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = {
	committed: string,
	tentative: string,
};

/**  Semantic kind of "working" phase, used to localize the spinner label. */
export type StreamWorkKind = "transcribing" | "polishing";

/**
 *  UI appearance mode. `System` follows the OS `prefers-color-scheme`; `Light`
 *  and `Dark` force one of the two palettes Handy already ships.
 */
export type Theme = "system" | "light" | "dark";

export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu";

export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool";

export type WindowsMicrophonePermissionStatus = {
	supported: boolean,
	overall_access: PermissionAccess,
	device_access: PermissionAccess,
	app_access: PermissionAccess,
	desktop_app_access: PermissionAccess,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

