name: "Windows Test Installer"

on: workflow_dispatch

jobs:
  windows-test-installer:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-latest"
      target: "x86_64-pc-windows-msvc"
      build-args: "--bundles nsis"
      sign-binaries: false
      use-test-identity: true
      asset-prefix: "ixiwhisper-windows-test"
      upload-artifacts: true
    secrets: inherit
